"""HoloMed AI - Core messaging dispatcher, subscription registry, tracing, and pipeline."""

from holomed.core.dead_letter import DeadLetterQueue
from holomed.core.dispatcher import MessageDispatcher
from holomed.core.exceptions import (
    CoreError,
    CorrelationError,
    CycleDetectedError,
    DeadLetterCapacityError,
    DispatcherLifecycleError,
    DuplicateSubscriptionError,
    HandlerExecutionError,
    InvalidHandlerResponseError,
    PayloadValidationError,
    PipelineError,
    PipelineRollbackError,
    PipelineStageExecutionError,
    PipelineTopologyError,
    RecursionDepthExceededError,
    SubscriptionCapacityError,
    SubscriptionError,
    TimestampValidationError,
    TopicValidationError,
    UnroutableMessageError,
)
from holomed.core.models import (
    DEFAULT_DLQ_CAPACITY,
    DEFAULT_FUTURE_TOLERANCE_SECONDS,
    DEFAULT_MAX_AGE_SECONDS,
    MAX_CORRELATION_LISTENERS,
    MAX_PAYLOAD_BYTES,
    MAX_PIPELINE_STAGES,
    MAX_RECURSION_DEPTH,
    MAX_SEGMENT_LENGTH,
    MAX_TOPIC_LENGTH,
    CommandRegistration,
    CorrelationCallback,
    CorrelationListener,
    DeadLetterOverflowPolicy,
    DeadLetterReason,
    DeadLetterRecord,
    DispatcherState,
    DispatchResult,
    EventHandler,
    EventSubscription,
    MessageHandler,
    PipelineResult,
    PipelineStageDescriptor,
    PipelineStageResult,
    PipelineStageStatus,
    QueryRegistration,
    StageExecutor,
    StageRollback,
)
from holomed.core.pipeline import PipelineCoordinator
from holomed.core.subscription import (
    SubscriptionRegistry,
    topic_matches,
    validate_concrete_topic,
    validate_topic_pattern,
)
from holomed.core.tracing import CausalTracer

__all__ = [
    # Core Exceptions
    "CoreError",
    "TopicValidationError",
    "SubscriptionError",
    "DuplicateSubscriptionError",
    "SubscriptionCapacityError",
    "UnroutableMessageError",
    "InvalidHandlerResponseError",
    "HandlerExecutionError",
    "DispatcherLifecycleError",
    "RecursionDepthExceededError",
    "CycleDetectedError",
    "CorrelationError",
    "PayloadValidationError",
    "TimestampValidationError",
    "DeadLetterCapacityError",
    "PipelineError",
    "PipelineTopologyError",
    "PipelineStageExecutionError",
    "PipelineRollbackError",
    # Models & Enums
    "DeadLetterReason",
    "DeadLetterOverflowPolicy",
    "DispatcherState",
    "PipelineStageStatus",
    "CommandRegistration",
    "QueryRegistration",
    "EventSubscription",
    "CorrelationListener",
    "DeadLetterRecord",
    "DispatchResult",
    "PipelineStageDescriptor",
    "PipelineStageResult",
    "PipelineResult",
    # Constants
    "MAX_TOPIC_LENGTH",
    "MAX_SEGMENT_LENGTH",
    "MAX_PAYLOAD_BYTES",
    "MAX_RECURSION_DEPTH",
    "MAX_CORRELATION_LISTENERS",
    "MAX_PIPELINE_STAGES",
    "DEFAULT_FUTURE_TOLERANCE_SECONDS",
    "DEFAULT_MAX_AGE_SECONDS",
    "DEFAULT_DLQ_CAPACITY",
    # Callables & Types
    "MessageHandler",
    "EventHandler",
    "CorrelationCallback",
    "StageExecutor",
    "StageRollback",
    # Services & Engines
    "DeadLetterQueue",
    "SubscriptionRegistry",
    "CausalTracer",
    "MessageDispatcher",
    "PipelineCoordinator",
    # Helpers
    "validate_concrete_topic",
    "validate_topic_pattern",
    "topic_matches",
]
