# -*- coding: utf-8 -*-
"""Phase F3.2-A Mathematical Swept Cut Surface Contract."""

from dataclasses import dataclass, field
import math
from typing import Tuple

from holomed.anatomy.models import Point3D, Vector3D
from holomed.anatomy.exceptions import AnatomyValidationError

UNIT_VECTOR_TOLERANCE = 1e-4
ORTHOGONALITY_TOLERANCE = 1e-4

@dataclass(frozen=True)
class TransportedFrame:
    """Rotation-Minimizing Frame (e.g. Bishop Frame) defining orientation at a sample."""
    tangent: Vector3D
    normal: Vector3D
    binormal: Vector3D

    def __post_init__(self):
        # Validate unit vectors
        t_mag = self.tangent.magnitude
        n_mag = self.normal.magnitude
        b_mag = self.binormal.magnitude

        if abs(t_mag - 1.0) > UNIT_VECTOR_TOLERANCE:
            raise AnatomyValidationError(f"Tangent is not a unit vector: mag={t_mag}")
        if abs(n_mag - 1.0) > UNIT_VECTOR_TOLERANCE:
            raise AnatomyValidationError(f"Normal is not a unit vector: mag={n_mag}")
        if abs(b_mag - 1.0) > UNIT_VECTOR_TOLERANCE:
            raise AnatomyValidationError(f"Binormal is not a unit vector: mag={b_mag}")

        # Validate orthogonality (dot products near 0)
        t_dot_n = self.tangent.dx * self.normal.dx + self.tangent.dy * self.normal.dy + self.tangent.dz * self.normal.dz
        t_dot_b = self.tangent.dx * self.binormal.dx + self.tangent.dy * self.binormal.dy + self.tangent.dz * self.binormal.dz
        n_dot_b = self.normal.dx * self.binormal.dx + self.normal.dy * self.binormal.dy + self.normal.dz * self.binormal.dz

        if abs(t_dot_n) > ORTHOGONALITY_TOLERANCE or abs(t_dot_b) > ORTHOGONALITY_TOLERANCE or abs(n_dot_b) > ORTHOGONALITY_TOLERANCE:
            raise AnatomyValidationError(f"Frame vectors are not orthogonal. Dots: T.N={t_dot_n}, T.B={t_dot_b}, N.B={n_dot_b}")
        
        # Enforce Right-Handed Basis (T x N ≈ B)
        cross_x = self.tangent.dy * self.normal.dz - self.tangent.dz * self.normal.dy
        cross_y = self.tangent.dz * self.normal.dx - self.tangent.dx * self.normal.dz
        cross_z = self.tangent.dx * self.normal.dy - self.tangent.dy * self.normal.dx
        
        if abs(cross_x - self.binormal.dx) > ORTHOGONALITY_TOLERANCE or \
           abs(cross_y - self.binormal.dy) > ORTHOGONALITY_TOLERANCE or \
           abs(cross_z - self.binormal.dz) > ORTHOGONALITY_TOLERANCE:
            raise AnatomyValidationError("Frame is not right-handed (T x N != B)")


@dataclass(frozen=True)
class SweptCutSurface:
    """
    Mathematical Swept Cut Surface representation.
    Freeform geometry derived from a processed tracking trajectory.
    
    Identity Semantics:
    - surface_id: Lineage identifier / string ID for tracking and serialization.
    - Mathematical Identity: Defined strictly by the sequence of centerline_samples,
      transport_frames, width, and thickness.
      
    Thickness Semantics:
    - `width`: Total lateral extent of the 2D cut surface (e.g., cutter width).
    - `thickness`: Extrusion scalar for future solid/volumetric conversion. 
      The current mathematical surface evaluates solely as a 2D ribbon 
      where thickness does NOT participate in evaluate_surface().
      
    Endpoint Semantics:
    - s=0 and s=L produce the mathematically open boundary edges.
    - Explicit future caps will be generated by the downstream volume generator if closed solids are required.
    """
    surface_id: str
    centerline_samples: Tuple[Point3D, ...]
    transport_frames: Tuple[TransportedFrame, ...]
    width: float
    thickness: float
    coordinate_space: str = "canonical_anatomical"
    cross_section_domain: Tuple[float, float] = field(default=(-0.5, 0.5))
    _arc_lengths: Tuple[float, ...] = field(init=False)

    def __post_init__(self):
        if not self.surface_id.strip():
            raise AnatomyValidationError("surface_id must be non-empty")
        if self.coordinate_space != "canonical_anatomical":
            raise AnatomyValidationError("Coordinate space must be canonical_anatomical")
        if not isinstance(self.width, (int, float)) or not math.isfinite(self.width):
            raise AnatomyValidationError("Width must be finite")
        if not isinstance(self.thickness, (int, float)) or not math.isfinite(self.thickness):
            raise AnatomyValidationError("Thickness must be finite")
        
        if self.width <= 0.0:
            raise AnatomyValidationError(f"Width must be strictly positive, got {self.width}")
        if self.thickness <= 0.0:
            raise AnatomyValidationError(f"Thickness must be strictly positive, got {self.thickness}")

        if len(self.centerline_samples) < 3:
            raise AnatomyValidationError(f"Insufficient centerline samples (<3), got {len(self.centerline_samples)}")
        if len(self.centerline_samples) != len(self.transport_frames):
            raise AnatomyValidationError("Length mismatch between centerline samples and transport frames")

        # Calculate arc lengths for parameter s
        arc_lengths = [0.0]
        for i in range(1, len(self.centerline_samples)):
            p1 = self.centerline_samples[i-1]
            p2 = self.centerline_samples[i]
            dx = p2.x - p1.x
            dy = p2.y - p1.y
            dz = p2.z - p1.z
            dist = math.sqrt(dx*dx + dy*dy + dz*dz)
            arc_lengths.append(arc_lengths[-1] + dist)

        object.__setattr__(self, "_arc_lengths", tuple(arc_lengths))

        if arc_lengths[-1] == 0.0:
            raise AnatomyValidationError("Zero-length path")

    @property
    def total_arc_length(self) -> float:
        """Returns the total arc length of the centerline (parameter L in meters)."""
        return self._arc_lengths[-1]

    def _interpolate_point(self, p1: Point3D, p2: Point3D, t: float) -> Point3D:
        return Point3D(
            x=p1.x + t * (p2.x - p1.x),
            y=p1.y + t * (p2.y - p1.y),
            z=p1.z + t * (p2.z - p1.z)
        )

    def _interpolate_binormal(self, b1: Vector3D, b2: Vector3D, t: float) -> Vector3D:
        dx = b1.dx + t * (b2.dx - b1.dx)
        dy = b1.dy + t * (b2.dy - b1.dy)
        dz = b1.dz + t * (b2.dz - b1.dz)
        mag = math.sqrt(dx*dx + dy*dy + dz*dz)
        if mag == 0:
            return b1
        return Vector3D(dx/mag, dy/mag, dz/mag)

    def evaluate_surface(self, s: float, u: float) -> Point3D:
        """
        Evaluates the continuous parameterized surface S(s, u).
        S(s, u) = C(s) + u * W * B(s)
        
        Args:
            s: Arc length parameter in meters (0 <= s <= total_arc_length).
            u: Cross-section parameter in cross_section_domain (typically [-0.5, 0.5]).
               u = 0 evaluates exactly to C(s).
               u = -0.5 is left edge, u = 0.5 is right edge.
        """
        if s < 0.0 or s > self.total_arc_length + 1e-6:
            raise AnatomyValidationError(f"s={s} is outside valid range [0, {self.total_arc_length}]")
        
        # Clamp near bounds for precision
        s = max(0.0, min(s, self.total_arc_length))
        
        # Binary search for the correct interval
        import bisect
        idx = bisect.bisect_right(self._arc_lengths, s)
        
        if idx == 0:
            c = self.centerline_samples[0]
            b = self.transport_frames[0].binormal
        elif idx >= len(self._arc_lengths):
            c = self.centerline_samples[-1]
            b = self.transport_frames[-1].binormal
        else:
            s0 = self._arc_lengths[idx - 1]
            s1 = self._arc_lengths[idx]
            t = (s - s0) / (s1 - s0) if s1 > s0 else 0.0
            
            c = self._interpolate_point(self.centerline_samples[idx - 1], self.centerline_samples[idx], t)
            b = self._interpolate_binormal(
                self.transport_frames[idx - 1].binormal,
                self.transport_frames[idx].binormal,
                t
            )
        
        return Point3D(
            x=c.x + u * self.width * b.dx,
            y=c.y + u * self.width * b.dy,
            z=c.z + u * self.width * b.dz
        )
