# -*- coding: utf-8 -*-
"""HoloMed Audio Subsystem (M02 — Spatial Audio & Acoustic Processing Foundation)."""

from holomed.audio.exceptions import (
    AudioCapacityError,
    AudioDeviceIdentityError,
    AudioEpochMismatchError,
    AudioError,
    AudioFrameValidationError,
    AudioLifecycleError,
    AudioPipelineError,
    AudioResourceIntegrityError,
    AudioSequenceError,
    AudioShutdownError,
    AudioValidationError,
)
from holomed.audio.models import (
    AcousticDirection,
    AcousticFeatures,
    AudioChannelRole,
    AudioChunk,
    AudioProcessingResult,
    AudioQuality,
    AudioTrack,
    ChannelLayout,
    MAX_AUDIO_CHANNELS,
    MAX_AUDIO_CHUNK_BYTES,
    MAX_AUDIO_DESCRIPTOR_BYTES,
    MAX_AUDIO_EVENTS,
    MAX_AUDIO_PAYLOAD_BYTES,
    MAX_AUDIO_PROCESSING_BUDGET_MS,
    MAX_AUDIO_TRACK_HISTORY,
    MAX_AUDIO_TRACKS,
    MAX_BUFFERED_AUDIO_CHUNKS,
    MicrophonePosition,
    SampleFormat,
    SlotState,
    TrackState,
    serialize_audio_payload,
)
from holomed.audio.pipeline import AudioPipeline
from holomed.audio.service import AudioService
from holomed.audio.spatial import SpatialAudioEstimator
from holomed.audio.spectral import AudioSpectralAnalyzer, radix2_fft, unpack_pcm_samples
from holomed.audio.store import AudioBufferStore
from holomed.audio.tracker import TemporalAcousticTracker

__all__ = [
    "AcousticDirection",
    "AcousticFeatures",
    "AudioBufferStore",
    "AudioCapacityError",
    "AudioChannelRole",
    "AudioChunk",
    "AudioDeviceIdentityError",
    "AudioEpochMismatchError",
    "AudioError",
    "AudioFrameValidationError",
    "AudioLifecycleError",
    "AudioPipeline",
    "AudioPipelineError",
    "AudioProcessingResult",
    "AudioQuality",
    "AudioResourceIntegrityError",
    "AudioSequenceError",
    "AudioService",
    "AudioShutdownError",
    "AudioSpectralAnalyzer",
    "AudioTrack",
    "AudioValidationError",
    "ChannelLayout",
    "MAX_AUDIO_CHANNELS",
    "MAX_AUDIO_CHUNK_BYTES",
    "MAX_AUDIO_DESCRIPTOR_BYTES",
    "MAX_AUDIO_EVENTS",
    "MAX_AUDIO_PAYLOAD_BYTES",
    "MAX_AUDIO_PROCESSING_BUDGET_MS",
    "MAX_AUDIO_TRACK_HISTORY",
    "MAX_AUDIO_TRACKS",
    "MAX_BUFFERED_AUDIO_CHUNKS",
    "MicrophonePosition",
    "SampleFormat",
    "SlotState",
    "SpatialAudioEstimator",
    "TemporalAcousticTracker",
    "TrackState",
    "radix2_fft",
    "serialize_audio_payload",
    "unpack_pcm_samples",
]
